import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jose Lopez - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main" className="container mx-auto font-sans py-2">
        <Header />
        <Hero />
      </main>
    </div>
  );
}
